### ISSUE TITLE
Build context referencing master branch?

### ISSUE THREAD

**Issue by daniel-gallagher** [Netflix/dispatch-docker#10]
The build context in `docker-compose.yml` is pointing at the master branch of the dispatch repo, but all of the bug fixes seem to be taking place in the `develop` branch. I imagine this should probably be changed at least temporarily so the bug fixes will be reflected when building the Docker images.

https://github.com/Netflix/dispatch-docker/blob/f65df7ca90e51ae2c72e87175efb5c275e6b21e0/docker-compose.yml#L7

**Comment by karl-johan-grahn** [comment]
This issue can be closed, this was fixed with https://github.com/Netflix/dispatch-docker/pull/20
