### ISSUE TITLE
fatal:  password authentication failed for user

### ISSUE THREAD

**Issue by sumansid** [Netflix/dispatch-docker#118]
I'm still getting the same error message : `fatal:  password authentication failed for user` even after setting the POSTGRES_USER and POSTGRES_PASSWORD and matching it with the DATABASE_CREDENTIALS.

_Originally posted by @sumansid in https://github.com/Netflix/dispatch-docker/issues/25#issuecomment-900532214_

**Comment by mvilanova** [comment]
@sumansid can you share a snippet of how you're setting them? Please redact the username and password if not the default ones.

**Comment by sumansid** [comment]
`POSTGRES_DB="dispatch_db"`
`POSTGRES_PASSWORD="dispatch_password"`
`POSTGRES_USER="dispatch_user"`
`DATABASE_CREDENTIALS="dispatch_user:dispatch_password"`
`DATABASE_NAME="dispatch_db"`
`DATABASE_PORT="5432"`


Here is the snippet

**Comment by mvilanova** [comment]
Snipped lgtm. Does the user with the password you're setting in the config file exist in the Postgres db?

**Comment by mvilanova** [comment]
Can you login to the docker postgres db using these credentials?

**Comment by sumansid** [comment]
Thanks ! will check it out and let you know
