### ISSUE TITLE
Building core service failing in docker-compose

### ISSUE THREAD

**Issue by rohit-dimagi** [Netflix/dispatch-docker#123]
The follwoing error is being encountered on running `docker-compose build core`
```
Step 38/48 : RUN set -x     && echo "deb http://apt.postgresql.org/pub/repos/apt buster-pgdg main" > /etc/apt/sources.list.d/pgdg.list     && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
 ---> Running in b04f1ed0b8c5
+ echo deb http://apt.postgresql.org/pub/repos/apt buster-pgdg main
+ wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc
/bin/sh: 1: wget: not found
+ apt-key add -
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
ERROR: Service 'core' failed to build: The command '/bin/sh -c set -x     && echo "deb http://apt.postgresql.org/pub/repos/apt buster-pgdg main" > /etc/apt/sources.list.d/pgdg.list     && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -' returned a non-zero code: 255
```

**Comment by smanikim** [comment]
I guess https://github.com/Netflix/dispatch/pull/1628 fixes issue

**Comment by smanikim** [comment]
I had same issue and it failed when I replaced below randomly to see if I am going to correct URL

![image](https://user-images.githubusercontent.com/9019390/135662878-38a6ab70-bcb1-4e77-9fcc-92998c48a3b2.png)


It was not fetching earlier as it was in cache.
[+] Building 0.5s (6/13)
 => CACHED [internal] load git source https://github.com/Netflix/dispatch.git#latest  
But I only started my testing 2 days ago, so weird for me

now it failed somewhere else but surprisingly this step passed

![image](https://user-images.githubusercontent.com/9019390/135662972-a298b571-d40a-40b1-bd90-d6e2f57109c7.png)

**Comment by Fgerthoffert** [comment]
> @Fgerthoffert if you replace context: github url to context: ../dispatch/ you can get it installed. I also needed to add wget and gnupg in the apt-get in Dockerfile I believe of ../dispatch/ if you cloned master.

Yes, that worked, thank you.
