### ISSUE TITLE
Install error: "No such service: dispatch

### ISSUE THREAD

**Issue by znb** [Netflix/dispatch-docker#14]
Installing on macOS I get the following error:

> Successfully tagged dispatch-local:latest
> Docker images built.
> Setting up database...
> ERROR: No such service: dispatch
> Cleaning up...

macOS: 10.15.2
Docker Desktop: 2.2.0.3
Docker Engine: 19.03.5
Compose: 1.25.4

Please let me know what sort of logs you need for investigation

**Comment by arnydo** [comment]
I had the same issue. It looks like there are some inconsistencies between the install script and the docker-compose file. The compose file creates these three services. 

* postgres
* web
* dispatch-scheduler

```
  postgres:
    <<: *restart_policy
    image: "postgres:9.6"
    volumes:
      - "dispatch-postgres:/var/lib/postgresql/data"
  web:
    <<: *dispatch_defaults
  dispatch-scheduler:
    <<: *dispatch_defaults
```

I changed the install script to reference `web` and was able to get further but ran into https://github.com/Netflix/dispatch-docker/pull/12#discussion_r385496718

**Comment by karl-johan-grahn** [comment]
Same issue for me

**Comment by kevgliss** [comment]
#12 has been merged.
