### ISSUE TITLE
Service 'web' failed to build

### ISSUE THREAD

**Issue by xiaopigfly** [Netflix/dispatch-docker#15]
`ERROR: Service 'web' failed to build: The command '/bin/sh -c set -x     && buildDeps=""     && apt-get update     && apt-get install -y --no-install-recommends $buildDeps     && pip install /tmp/dist/*.whl     && apt-get purge -y --auto-remove $buildDeps     && apt-get install -y --no-install-recommends     pkg-config         && apt-get clean     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100`

**Comment by xiaopigfly** [comment]
Now:
`Successfully built f578f2092e18
Successfully tagged dispatch-local:latest

Docker images built.

Setting up database...
ERROR: No such service: dispatch
Cleaning up...`

**Comment by juanvasquezreyes** [comment]
> `ERROR: Service 'web' failed to build: The command '/bin/sh -c set -x && buildDeps="" && apt-get update && apt-get install -y --no-install-recommends $buildDeps && pip install /tmp/dist/*.whl && apt-get purge -y --auto-remove $buildDeps && apt-get install -y --no-install-recommends pkg-config && apt-get clean && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100`

**Comment by juanvasquezreyes** [comment]
What did you do to fix the first issue?

**Comment by kyfer** [comment]
Had the same issue.
Fixed by ensuring Docker Desktop was updated to 2.2.0.4

**Comment by sarahcthekey** [comment]
> What did you do to fix the first issue?

I had the same issue, the error directly before it when building 'web' was:
`E: Release file for http://deb.debian.org/debian/dists/buster-updates/InRelease is not valid yet (invalid for another 29min 6s). Updates for this repository will not be applied.
`
I waited the specified amount of time and re-ran it fine.

**Comment by kevgliss** [comment]
We've made several updates, please try again and open a new issue if you run into any issues.
