### ISSUE TITLE
Basic Install Failing to Build "Core"

### ISSUE THREAD

**Issue by elixir-gdsc** [Netflix/dispatch-docker#151]
**Describe the bug**
When running a fresh install, Ubuntu 22.04 or Windows 11, build is failing on the 'core' service. 

```
python: can't open file '/usr/src/dispatch/setup.py': [Errno 2] No such file or directory
Removing intermediate container 
The command '/bin/sh -c export YARN_CACHE_FOLDER="$(mktemp -d)"     && cd /usr/src/dispatch     && python setup.py bdist_wheel     && rm -r "$YARN_CACHE_FOLDER"     && mv /usr/src/dispatch/dist /dist' returned a non-zero code: 2
ERROR: Service 'core' failed to build : Build failed
```
No customization was done, just following the basic instructions for install. 

**To Reproduce**

1. Start new instance
2.  Clone Repo
3. Run ./install.sh
4. Build fails at the previously mentioned step

**Expected behavior**
Build should complete correctly

**Comment by elixir-gdsc** [comment]
I believe the issue is in the Dockerfile in https://github.com/Netflix/dispatch/blob/master/docker/Dockerfile

The COPY command isn't working correctly. I tested this locally, by removing the docker directory. and putting those files in the root. Worked fine.

**Comment by elixir-gdsc** [comment]
Or, you could revert the changes in commit: https://github.com/Netflix/dispatch-docker/commit/ba06f75c7287d65d3207ef594aada35970765bba which will also allow it to build.

**Comment by elixir-gdsc** [comment]
This is still an issue. Build will fail with the current commit. Should be reverted or fixed downstream.

**Comment by badan-cloud** [comment]
This issue is still there. You've introduced a regression in your latest commit.

**Comment by elixir-gdsc** [comment]
Is this project no longer being maintained?
