### ISSUE TITLE
Environment Variable GOOGLE_SERVICE_ACCOUNT_DELAGATED_ACCOUNT Typo

### ISSUE THREAD

**Issue by njoerd114** [Netflix/dispatch-docker#18]
in the .env file it is defined as GOOGLE_SERVICE_ACCOUNT_DELAGATED_ACCOUNT, in the application as well, the documentation under https://hawkins.gitbook.io/dispatch/configuration/plugins/configuring-g-suite#google_service_account_delegated_account
however says: "GOOGLE_SERVICE_ACCOUNT_DELEGATED_ACCOUNT" which seems to be more correct to me.

**Comment by mvilanova** [comment]
Merged your changes. Thanks!
