### ISSUE TITLE
How to configure “JWKS_URL” in .env file of Dispatch?

### ISSUE THREAD

**Issue by AnthonyLzq** [Netflix/dispatch-docker#22]
I was checking the [.env example](https://hawkins.gitbook.io/dispatch/installation) that is mentioned in the [documentation](https://github.com/Netflix/dispatch/blob/develop/docker/.env.example), but I don't have a clue of what to put in JWKS_URL=.

What am I supposed to put there?

**Comment by kevgliss** [comment]
What auth provider do you hope to use? JWKS_URL if you're using the PKCE auth flow you need a provider that supports that flow. The URL itself will be the URL to the public key for the incoming JWKS token.

**Comment by karl-johan-grahn** [comment]
The auth can be disabled with these args, correct?
```
DISPATCH_PKCE_AUTH_ENABLED="False"
VUE_APP_DISPATCH_PKCE_AUTH="False"
JWKS_URL="None"
```

**Comment by AnthonyLzq** [comment]
You were right @karl-johan-grahn, thanks for your advice.
