### ISSUE TITLE
postgress password hostname and db settings.

### ISSUE THREAD

**Issue by mindfunk** [Netflix/dispatch-docker#25]
Apologies, as this is the only forum I am aware of to ask this question. I do not know of any dispatch specific forums. If they exist, please let me know.

I cloned, copied over the .env.example to .env . I made a few adjustments, and ran install.sh

I am not sure what to set these values to:
DATABASE_CREDENTIALS=creds
DATABASE_HOSTNAME=postgres
DATABASE_NAME=dispatch
DATABASE_PORT=5432

Where are the default creds set? I've tried just putting a value in for the credentials, but I get the error below. Presubably, the install.sh script is building the postgress container. I would assume, when it did so, it would set a password. So, what is the default password for this? Or is there a postgres,.conf file (not found) that I need to modify? What is the right thing to do here?

----
Docker images built.

Setting up database...
Usage: dispatch [OPTIONS] COMMAND [ARGS]...

  Command-line interface to Dispatch.

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  contact    All commands for contact...
  database   Container for all dispatch
             database...

  incident   All commands for incident...
  plugins    All commands for plugin...
  scheduler  Container for all dispatch...
  server     Container for all dispatch server...
  term       All commands for term manipulation.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2285, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
 File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 657, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 652, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 488, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: fe_sendauth: no password supplied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/dispatch", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 811, in entrypoint
    dispatch_cli()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 592, in upgrade_database
    alembic_command.upgrade(alembic_cfg, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.8/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.8/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.8/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/dispatch/alembic/env.py", line 84, in <module>
    run_migrations_online()
  File "/usr/local/lib/python3.8/site-packages/dispatch/alembic/env.py", line 74, in run_migrations_online
    with connectable.connect() as connection:
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2218, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 103, in __init__
    else engine.raw_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2317, in raw_connection
    return self._wrap_pool_connect(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2288, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1554, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2285, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 657, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 652, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 488, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) fe_sendauth: no password supplied

(Background on this error at: http://sqlalche.me/e/e3q8)
Cleaning up...

**Comment by B3lak0r** [comment]
Hi,

Please try it like this:

DATABASE_CREDENTIALS=dispatch:dispatch

> Apologies, as this is the only forum I am aware of to ask this question. I do not know of any dispatch specific forums. If they exist, please let me know.
> 
> I cloned, copied over the .env.example to .env . I made a few adjustments, and ran install.sh
> 
> I am not sure what to set these values to:
> DATABASE_CREDENTIALS=creds
> DATABASE_HOSTNAME=postgres
> DATABASE_NAME=dispatch
> DATABASE_PORT=5432
> 
> Where are the default creds set? I've tried just putting a value in for the credentials, but I get the error below. Presubably, the install.sh script is building the postgress container. I would assume, when it did so, it would set a password. So, what is the default password for this? Or is there a postgres,.conf file (not found) that I need to modify? What is the right thing to do here?
> 
> Docker images built.
> 
> Setting up database...
> Usage: dispatch [OPTIONS] COMMAND [ARGS]...
> 
> Command-line interface to Dispatch.
> 
> Options:
> --version Show the version and exit.
> --help Show this message and exit.
> 
> Commands:
> contact All commands for contact...
> database Container for all dispatch
> database...
> 
> incident All commands for incident...
> plugins All commands for plugin...
> scheduler Container for all dispatch...
> server Container for all dispatch server...
> term All commands for term manipulation.
> Traceback (most recent call last):
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2285, in _wrap_pool_connect
> return fn()
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
> return _ConnectionFairy._checkout(self)
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout
> fairy = _ConnectionRecord.checkout(pool)
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
> rec = pool._do_get()
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
> return self._create_connection()
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 437, in **init**
> self.__connect(first_connect_check=True)
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 657, in __connect pool.logger.debug("Error on connect(): %s", e) File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in **exit** compat.raise_( File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
> raise exception
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 652, in __connect
> connection = pool._invoke_creator(self)
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
> return dialect.connect(*cargs, **cparams)
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 488, in connect
> return self.dbapi.connect(*cargs, **cparams)
> File "/usr/local/lib/python3.8/site-packages/psycopg2/**init**.py", line 126, in connect
> conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
> psycopg2.OperationalError: fe_sendauth: no password supplied
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
> File "/usr/local/bin/dispatch", line 8, in
> sys.exit(entrypoint())
> File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 811, in entrypoint
> dispatch_cli()
> File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in **call**
> return self.main(*args, **kwargs)
> File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
> rv = self.invoke(ctx)
> File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
> return _process_result(sub_ctx.command.invoke(sub_ctx))
> File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
> return _process_result(sub_ctx.command.invoke(sub_ctx))
> File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
> return ctx.invoke(self.callback, **ctx.params)
> File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
> return callback(*args, **kwargs)
> File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 592, in upgrade_database
> alembic_command.upgrade(alembic_cfg, revision, sql=sql, tag=tag)
> File "/usr/local/lib/python3.8/site-packages/alembic/command.py", line 298, in upgrade
> script.run_env()
> File "/usr/local/lib/python3.8/site-packages/alembic/script/base.py", line 489, in run_env
> util.load_python_file(self.dir, "env.py")
> File "/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
> module = load_module_py(module_id, path)
> File "/usr/local/lib/python3.8/site-packages/alembic/util/compat.py", line 184, in load_module_py
> spec.loader.exec_module(module)
> File "", line 783, in exec_module
> File "", line 219, in _call_with_frames_removed
> File "/usr/local/lib/python3.8/site-packages/dispatch/alembic/env.py", line 84, in
> run_migrations_online()
> File "/usr/local/lib/python3.8/site-packages/dispatch/alembic/env.py", line 74, in run_migrations_online
> with connectable.connect() as connection:
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2218, in connect
> return self._connection_cls(self, **kwargs)
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 103, in **init**
> else engine.raw_connection()
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2317, in raw_connection
> return self._wrap_pool_connect(
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2288, in _wrap_pool_connect
> Connection._handle_dbapi_exception_noconnection( File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1554, in _handle_dbapi_exception_noconnection util.raise_( File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
> raise exception
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2285, in _wrap_pool_connect
> return fn()
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
> return _ConnectionFairy._checkout(self)
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout
> fairy = _ConnectionRecord.checkout(pool)
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
> rec = pool._do_get()
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
> return self._create_connection()
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
> return _ConnectionRecord(self)
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 437, in **init**
> self.__connect(first_connect_check=True)
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 657, in __connect pool.logger.debug("Error on connect(): %s", e) File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in **exit** compat.raise_( File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
> raise exception
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 652, in __connect
> connection = pool._invoke_creator(self)
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
> return dialect.connect(*cargs, **cparams)
> File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 488, in connect
> return self.dbapi.connect(*cargs, **cparams)
> File "/usr/local/lib/python3.8/site-packages/psycopg2/**init**.py", line 126, in connect
> conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
> sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) fe_sendauth: no password supplied
> 
> (Background on this error at: http://sqlalche.me/e/e3q8)
> Cleaning up...

Please adjust the credentials on the .env file like this:

DATABASE_CREDENTIALS=dispatch:dispatch

The format must always be  user:pass

**Comment by sarahcthekey** [comment]
> Hi,
> 
> Please try it like this:
> 
> DATABASE_CREDENTIALS=dispatch:dispatch
> 
> The format must always be user:pass
> 
> > Apologies, as this is the only forum I am aware of to ask this question. I do not know of any dispatch specific forums. If they exist, please let me know.
> > I cloned, copied over the .env.example to .env . I made a few adjustments, and ran install.sh
> > I am not sure what to set these values to:
> > DATABASE_CREDENTIALS=creds
> > DATABASE_HOSTNAME=postgres
> > DATABASE_NAME=dispatch
> > DATABASE_PORT=5432
> > Where are the default creds set? I've tried just putting a value in for the credentials, but I get the error below. Presubably, the install.sh script is building the postgress container. I would assume, when it did so, it would set a password. So, what is the default password for this? Or is there a postgres,.conf file (not found) that I need to modify? What is the right thing to do here?
> > Docker images built.
> > Setting up database...
> > Usage: dispatch [OPTIONS] COMMAND [ARGS]...
> > Command-line interface to Dispatch.
> > Options:
> > --version Show the version and exit.
> > --help Show this message and exit.
> > Commands:
> > contact All commands for contact...
> > database Container for all dispatch
> > database...
> > incident All commands for incident...
> > plugins All commands for plugin...
> > scheduler Container for all dispatch...
> > server Container for all dispatch server...
> > term All commands for term manipulation.
> > Traceback (most recent call last):
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2285, in _wrap_pool_connect
> > return fn()
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
> > return _ConnectionFairy._checkout(self)
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout
> > fairy = _ConnectionRecord.checkout(pool)
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
> > rec = pool._do_get()
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
> > return self._create_connection()
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 437, in **init**
> > self.__connect(first_connect_check=True)
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 657, in __connect pool.logger.debug("Error on connect(): %s", e) File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in **exit** compat.raise_( File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
> > raise exception
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 652, in __connect
> > connection = pool._invoke_creator(self)
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
> > return dialect.connect(*cargs, **cparams)
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 488, in connect
> > return self.dbapi.connect(*cargs, **cparams)
> > File "/usr/local/lib/python3.8/site-packages/psycopg2/**init**.py", line 126, in connect
> > conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
> > psycopg2.OperationalError: fe_sendauth: no password supplied
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last):
> > File "/usr/local/bin/dispatch", line 8, in
> > sys.exit(entrypoint())
> > File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 811, in entrypoint
> > dispatch_cli()
> > File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in **call**
> > return self.main(*args, **kwargs)
> > File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
> > rv = self.invoke(ctx)
> > File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
> > return _process_result(sub_ctx.command.invoke(sub_ctx))
> > File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
> > return _process_result(sub_ctx.command.invoke(sub_ctx))
> > File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
> > return ctx.invoke(self.callback, **ctx.params)
> > File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
> > return callback(*args, **kwargs)
> > File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 592, in upgrade_database
> > alembic_command.upgrade(alembic_cfg, revision, sql=sql, tag=tag)
> > File "/usr/local/lib/python3.8/site-packages/alembic/command.py", line 298, in upgrade
> > script.run_env()
> > File "/usr/local/lib/python3.8/site-packages/alembic/script/base.py", line 489, in run_env
> > util.load_python_file(self.dir, "env.py")
> > File "/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
> > module = load_module_py(module_id, path)
> > File "/usr/local/lib/python3.8/site-packages/alembic/util/compat.py", line 184, in load_module_py
> > spec.loader.exec_module(module)
> > File "", line 783, in exec_module
> > File "", line 219, in _call_with_frames_removed
> > File "/usr/local/lib/python3.8/site-packages/dispatch/alembic/env.py", line 84, in
> > run_migrations_online()
> > File "/usr/local/lib/python3.8/site-packages/dispatch/alembic/env.py", line 74, in run_migrations_online
> > with connectable.connect() as connection:
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2218, in connect
> > return self._connection_cls(self, **kwargs)
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 103, in **init**
> > else engine.raw_connection()
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2317, in raw_connection
> > return self._wrap_pool_connect(
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2288, in _wrap_pool_connect
> > Connection._handle_dbapi_exception_noconnection( File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1554, in _handle_dbapi_exception_noconnection util.raise_( File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
> > raise exception
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2285, in _wrap_pool_connect
> > return fn()
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
> > return _ConnectionFairy._checkout(self)
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout
> > fairy = _ConnectionRecord.checkout(pool)
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
> > rec = pool._do_get()
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
> > return self._create_connection()
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
> > return _ConnectionRecord(self)
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 437, in **init**
> > self.__connect(first_connect_check=True)
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 657, in __connect pool.logger.debug("Error on connect(): %s", e) File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in **exit** compat.raise_( File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
> > raise exception
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 652, in __connect
> > connection = pool._invoke_creator(self)
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
> > return dialect.connect(*cargs, **cparams)
> > File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 488, in connect
> > return self.dbapi.connect(*cargs, **cparams)
> > File "/usr/local/lib/python3.8/site-packages/psycopg2/**init**.py", line 126, in connect
> > conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
> > sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) fe_sendauth: no password supplied
> > (Background on this error at: http://sqlalche.me/e/e3q8)
> > Cleaning up...

I tried this and I got the error for invalid password now, any ideas?

  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 652, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 488, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
**sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "dispatch"**

(Background on this error at: http://sqlalche.me/e/e3q8)
Cleaning up...

**Comment by B3lak0r** [comment]
@mindfunk my previous post was assuming you also have these:

DATABASE_CREDENTIALS=dispatch:dispatch
POSTGRES_PASSWORD=dispatch
POSTGRES_USER=dispatch

**Comment by kendung** [comment]
I encountered the same errors. Thanks for the post.

**Comment by tuctboh** [comment]
Running into the exact same problem, and my settings are -

```
# Database
DATABASE_CREDENTIALS=dispatch:w00bly
DATABASE_HOSTNAME=postgres
DATABASE_NAME=dispatch
DATABASE_PORT=5432
POSTGRES_DB=dispatch
POSTGRES_PASSWORD=w00bly
POSTGRES_USER=dispatch
```

I've tried it with "dispatch:dispatch" too.

Tuc

**Comment by diogomatsubara** [comment]
Try with `postgres:dispatch`, that is user `postgres`, password `dispatch`.  AFAICT, the installation doesn't create the `dispatch` user in the PG database.  Even if you define the POSTGRES_* variables, I don't see anywhere in the code that is used, so I think it's just using the defaults.

**Comment by kevgliss** [comment]
I've updated the example env with the correct default parameters. An important note that I think is covered above but want to highlight:

DATABASE_CREDENTIALS=username:password

must match:

POSTGRES_USER=username
POSTGRES_PASSWORD=passwoird

**Comment by sumansid** [comment]
I'm still getting the same error message : `fatal:  password authentication failed for user` even after setting the POSTGRES_USER and POSTGRES_PASSWORD and matching it with the DATABASE_CREDENTIALS.

**Comment by vikassinha2019** [comment]
looks like the "fatal: password authentication failed for user" is still there during ./install.sh. I am also facing this issue

**Comment by vikassinha2019** [comment]
removing the docker volume 'dispatch-postgres' and re-run the install.sh script resolved the issue for me.
