### ISSUE TITLE
[SQL: ALTER TABLE application ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE]

### ISSUE THREAD

**Issue by B3lak0r** [Netflix/dispatch-docker#26]
Everything set up on .env file, but at the end of the installation I'm getting this error:

 File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "application" does not exist

-------------------------------------------------------------------------------------------------------------
Docker images built.
Creating network "dispatch_default" with the default driver
Creating dispatch_postgres_1 ... done
Setting up database...
Starting dispatch_postgres_1 ... done                                                                                   Usage: dispatch [OPTIONS] COMMAND [ARGS]...

  Command-line interface to Dispatch.

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  contact    All commands for contact manipulation.
  database   Container for all dispatch database commands.
  incident   All commands for incident manipulation.
  plugins    All commands for plugin manipulation.
  scheduler  Container for all dispatch scheduler commands.
  server     Container for all dispatch server commands.
  term       All commands for term manipulation.
Starting dispatch_postgres_1 ... done                                                                                   INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> e75e103693f2, Initial migration
INFO  [alembic.runtime.migration] Running upgrade e75e103693f2 -> d0501fc6be89, empty message
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "application" does not exist

**Comment by ZPerling** [comment]
@B3lak0r  same error...

**Comment by devvesa** [comment]
Same here

**Comment by sarahcthekey** [comment]
+1 on this error

**Comment by sarahcthekey** [comment]
FYI I got dispatch to build fully by commenting out the upgrade part of install.sh. 
This may have impact on the app, I've yet to find out, but at least it's running successfully in docker now.

`echo "Setting up database..."
if [ $CI ]; then
  docker-compose run web --help
 # docker-compose run web database upgrade --no-input
else
  docker-compose run web --help
#  docker-compose run web database upgrade
fi

cleanup`

**Comment by B3lak0r** [comment]
@sarahcthekey but even after doing that no web UI at all, did you get it functional?

**Comment by sarahcthekey** [comment]
> @sarahcthekey but even after doing that no web UI at all, did you get it functional?

I didn’t get a web UI no... I did notice there was no port forward from my VM to the container though when I ran docker ps (only stated port 8000 on container was running)

Dispatch was running as I checked, i ran an exec into the container and ran dispatch —help

Still something not quite right.

**Comment by B3lak0r** [comment]
@sarahcthekey regarding the port forwarding just add something like this on your docker-compose.yml:

version: "3.4"
x-restart-policy: &restart_policy
  restart: unless-stopped
x-dispatch-defaults: &dispatch_defaults
  <<: *restart_policy
  env_file:
    - .env
  build:
    # Pro-tip: point this to a relative directory containing the Dispatch
    # project root to pick up changes from your dev environment
    # (e.g., ../dispatch-root)
    context: https://github.com/Netflix/dispatch.git#develop:.
  image: dispatch-local
  depends_on:
    - postgres
  env_file:
    - .env
services:
  postgres:
    <<: *restart_policy
    env_file:
      - .env
    image: "postgres:9.6"
    ports:
      - "5432:5432"
    volumes:
      - "dispatch-postgres:/var/lib/postgresql/data"
    env_file: ./.env
  web:
    <<: *dispatch_defaults
    command: ["server", "start", "dispatch.main:app"]
    ports:
      - "8000:8000"
  dispatch-scheduler:
    <<: *dispatch_defaults
    command: ["scheduler", "start"]
    ports:
      - "8001:8000"
volumes:
  dispatch-postgres:
    external: true

I'll keep working on it to see if I can get this functional.

**Comment by sarahcthekey** [comment]
@B3lak0r Perfect thanks, I will add the port config into the docker compose file tomorrow and give that a go. 

If I manage to get a web UI running I’ll let you know too, hopefully we get there soon :-)

**Comment by sarahcthekey** [comment]
@B3lak0r Added the port forward however still no UI. Points to note for the moment:

- docker ps shows the port forward correctlly (listening on 0.0.0.0:8000->8000)
- netstat on VM running docker shows the port forward listening 
- running a curl request to 127.0.0.1:8000 on VM returns curl error 52 'Empty reply from server'
- running a curl request inside the container to 127.0.0.1:8000 I get a valid response and can see the HTML config for the web UI
- browsing to the public IP of my VM instance running the docker container returns nothing on port 8000 (firewall rules definitely in place)
- nmap to public IP of my VM returns port 8000 but listed as 'closed'

It now looks like a port forward or network issue...

**Comment by B3lak0r** [comment]
@sarahcthekey it seems so, same situation here right now, btw are you able to run these dispatch cli commands successfully:

dispatch server config (returns empty)
dispatch server shell (trows an iphyton error)
dispatch database list (command not found??)

**Comment by sarahcthekey** [comment]
@B3lak0r I edited my above comment, tried to access via docker container on same network and still got connection refused.

On your commands I get all the same output apart from I get errors about invalid and empty values for JIRA etc from the env file, but I've left them empty for the moment as I wanted to get the web UI up and running first so that's expected. 

On the last one the only commands available that I can see and work are:

```
root@260b30af181b:/# dispatch database --help
Usage: dispatch database [OPTIONS] COMMAND [ARGS]...

  Container for all dispatch database commands.

Options:
  --help  Show this message and exit.

Commands:
  downgrade      Downgrades database schema to next newest version.
  drop           Drops all data in database.
  dump           Dumps the database via pg_dump.
  heads          Shows the heads of the database.
  history        Shows the history of the database.
  init           Initializes a new database.
  restore        Restores the database via pg_restore.
  revision       Create new database revision.
  sync-triggers  Ensures that all database triggers have been installed.
  upgrade        Upgrades database schema to newest version.
```

**Comment by sarahcthekey** [comment]
@B3lak0r Found the issue.

The web app container is listening on localhost only, rather than 0.0.0.0. Despite it saying in the Dockerfile here in their dispatch repo : https://github.com/Netflix/dispatch/blob/develop/docker/Dockerfile 

```
ENTRYPOINT ["dispatch"]
CMD ["server", "start", "dispatch.main:app", "--host=0.0.0.0"]
```

I built the docker image locally using this repo, then ran:
`docker run dispatch-sc --detach --env-file ../dispatch-docker/.en`

Can now access publicly. So it's an issue in the Docker Compose build, must be ignoring the --host=0.0.0.0 when starting dispatch or something (or Docker Compose is building from a Docker image not based on the Dockerfile containing the host config?!)

**Comment by B3lak0r** [comment]
@ZPerling @devvesa @jfernandez  the solution by order:

https://github.com/Netflix/dispatch-docker/issues/26#issuecomment-604349500

https://github.com/Netflix/dispatch-docker/issues/32#issuecomment-604447519

**Comment by tomarv2** [comment]
getting error when trying to use the UI:

```
INFO:     172.25.0.1:50642 - "GET /static/js/routing-table.b8b29268.js HTTP/1.1" 304 Not Modified
INFO:     172.25.0.1:50652 - "GET /static/js/tag-table.6ed4a534.js HTTP/1.1" 304 Not Modified
INFO:     172.25.0.1:50640 - "GET /static/js/service-table.f73368a8.js HTTP/1.1" 304 Not Modified
INFO:     172.25.0.1:50646 - "GET /static/js/search-result-list.b9284704.js HTTP/1.1" 304 Not Modified
INFO:     172.25.0.1:50650 - "GET /static/js/team-table.a93a3070.js HTTP/1.1" 304 Not Modified
INFO:     172.25.0.1:50650 - "GET /api/v1/incident_types/?itemsPerPage=50&sortBy[]=name&descending[]=false HTTP/1.1" 401 Unauthorized
INFO:     172.25.0.1:50642 - "GET /api/v1/incident_priorities/ HTTP/1.1" 401 Unauthorized
INFO:     172.25.0.1:50654 - "POST /api/v1/incidents/ HTTP/1.1" 401 Unauthorized
```

**Comment by kevgliss** [comment]
This is a combination of things, but it boils down to the fact that our `upgrade` command wasn't smart enough to create the tables. https://github.com/Netflix/dispatch/pull/268 should resolve this issue. Apologies on the delay.
