### ISSUE TITLE
DISPATCH_UI_URL is missing

### ISSUE THREAD

**Issue by Extazer583** [Netflix/dispatch-docker#29]
Hello,

Some one can help me, i have no error juste in the end

thx !!

Setting up database...
Starting dispatch-docker_postgres_1 ... done
Traceback (most recent call last):
  File "/usr/local/bin/dispatch", line 5, in <module>
    from dispatch.cli import entrypoint
  File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 12, in <module>
    from dispatch import __version__, config
  File "/usr/local/lib/python3.8/site-packages/dispatch/config.py", line 66, in <module>
    DISPATCH_UI_URL = config("DISPATCH_UI_URL")
  File "/usr/local/lib/python3.8/site-packages/starlette/config.py", line 62, in __call__
    return self.get(key, cast, default)
  File "/usr/local/lib/python3.8/site-packages/starlette/config.py", line 75, in get
    raise KeyError(f"Config '{key}' is missing, and has no default.")
KeyError: "Config 'DISPATCH_UI_URL' is missing, and has no default."
![Capture d’écran de 2020-03-24 12-33-26](https://user-images.githubusercontent.com/46268206/77421481-36e5b080-6dcc-11ea-8e60-ced7e592bb4a.png)

**Comment by mvilanova** [comment]
@Extazer583 `DISPATCH_UI_URL` was added in https://github.com/Netflix/dispatch/pull/141 to allow us to construct the URL to the active incidents detail page. Add it to your `.env` file and set it to your Dispatch server URL (e.g. `https://dispatch.example.com`).

**Comment by Extazer583** [comment]
thx now it's INCIDENT_CONVERSATION_COMMANDS_REFERENCE_DOCUMENT_ID :/

**Comment by mvilanova** [comment]
This is the id for the Slack / commands reference sheet. You can set it to `INCIDENT_CONVERSATION_COMMANDS_REFERENCE_DOCUMENT_ID` until you have one.

**Comment by Extazer583** [comment]
yes it's good thank
