### ISSUE TITLE
what is the url when it's full done 

### ISSUE THREAD

**Issue by Extazer583** [Netflix/dispatch-docker#31]
Hi,
sorry i'm not docker expert but it's full done after the ./install.sh and docker-compose up -d it's full done too
i try localhost on my brower but it's doesn't work same thing in https..

Can you help me plz

**Comment by sarahcthekey** [comment]
Hi @Extazer583 are you running this locally on your laptop?

You'll need to check a couple of things, when you run **docker ps** does it show 0.0.0.0:8000->8000/tcp in the ports column for dispatch-web container?

**Comment by Extazer583** [comment]
Hi @sarahcthekey 
No :/

root@H4ckbook:~/dispatch-docker# 
root@H4ckbook:~/dispatch-docker# docker ps
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                    NAMES
d9160e2dfc50        dispatch-local-web         "dispatch server sta…"   29 seconds ago      Up 27 seconds       8000/tcp                 dispatch_web_1
8d0c9e50489f        dispatch-local-scheduler   "dispatch scheduler …"   29 seconds ago      Up 27 seconds       8000/tcp                 dispatch_scheduler_1
3d651d2c7e66        postgres:9.6               "docker-entrypoint.s…"   3 minutes ago       Up 28 seconds       0.0.0.0:5432->5432/tcp   dispatch_postgres_1

**Comment by Extazer583** [comment]
it's good the port redirect was'nt specified in docker-compose.yml :)

 image: dispatch-local-scheduler
    depends_on:
      - postgres
    env_file:
      - .env
    command: ["scheduler", "start"]
    ports:
    - "8000:8000"
volumes:
  dispatch-postgres:
    external: true

**Comment by Extazer583** [comment]
close
