### ISSUE TITLE
./install fail gosu

### ISSUE THREAD

**Issue by kwent** [Netflix/dispatch-docker#42]
```
ERROR: Service 'web' failed to build: The command '/bin/sh -c set -x     && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)"     && wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc"     && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu     && rm -r /usr/local/bin/gosu.asc     && chmod +x /usr/local/bin/gosu' returned a non-zero code: 2
Cleaning up...
```

**Comment by tomarv2** [comment]
@kwent you can try this: tomarv2/dispatch-local-web I build it couple of days ago without any issue.

**Comment by kwent** [comment]
@tomarv2 The branch your mentioned is not available remotely on this repo unfortunately.

**Comment by tomarv2** [comment]
Sorry I dint put it correctly, it’s a docker image that I built and pushed to docker hub. Try pulling from the.

**Comment by kpolako** [comment]
Hello,

I've ecountered the same error. The build fails on `gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu`, returns `gpg: BAD signature from "Tianon Gravi <tianon@tianon.xyz>" [unknown]` message and output that @kwent has mentioned.
And, to be honest, I don't know how to cope with it.

**Comment by kevgliss** [comment]
Are you still having this issue? I've built the images correctly today without issue.

**Comment by kwent** [comment]
No i'm getting using last master

```
Generating secret key...
sed: 1: "./.env": invalid command code .
Cleaning up...
```

**Comment by mvilanova** [comment]
@kwent the behavior of some command line utilities like `sed` differ a little bit between platforms some times. #47 removes the need of using `sed` for creating a copying the `.env.example` file.

**Comment by kwent** [comment]
No improvements :(

This is not this line which is failing for me.

This one is https://github.com/Netflix/dispatch-docker/blob/master/install.sh#L71 @mvilanova

**Comment by mvilanova** [comment]
I was able to repro on macOS 10.15.3. I'll cut a PR to fix it.

**Comment by mvilanova** [comment]
@kwent ok, I think I got it fixed. Please try again and let me know.

**Comment by kwent** [comment]
We are getting there slowly...

Now having

```
ERROR: Service 'web' failed to build: The command '/bin/sh -c set -x     && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)"     && wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc"     && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu     && rm -r /usr/local/bin/gosu.asc     && chmod +x /usr/local/bin/gosu' returned a non-zero code: 2
Cleaning up...
```

Which was the original issue

**Comment by mvilanova** [comment]
@kwent this is an issue related to the keyserver the Docker build process uses, not an issue with Dispatch. See https://github.com/docker-library/postgres/issues/523 and https://github.com/docker-library/mysql/issues/170#issuecomment-220675705 on how to potentially fix the issue.
