### ISSUE TITLE
Run without Configuring?

### ISSUE THREAD

**Issue by Joe-Galante** [Netflix/dispatch-docker#44]
I would like to run Dispatch "as is" so I can get a sense of what Dispatch is like when its running.  I'd like to not do any configuration of my G Suite, Slack, etc.   When I copy .env.example to .env and run install.sh I get the following error.  Is it possible run Dispatch as a  demos without configuring?

`Checking minimum requirements...

./.env already exists, skipped creation.
./requirements.txt already exists, skipped creation.
Removing network dispatch_default
WARNING: Network dispatch_default not found.

Creating volumes for persistent storage...
Created dispatch-postgres.

Generating secret key...
sed: 1: "./.env": invalid command code .
Cleaning up...`

**Comment by Joe-Galante** [comment]
This is no longer an issue for me.  I was able to satisfy .env requirements and proceed with installation.

**Comment by ryancl** [comment]
I had this exact problem. I would love to know how you got past it if you wouldn't mind sharing.

**Comment by ceej21** [comment]
Yes, can you please share? I am trying to do this as well

**Comment by mvilanova** [comment]
The `sed` issue was fixed in https://github.com/Netflix/dispatch-docker/commit/68fbbb5ea3fb77ffb48775dac78ce124a6716248. Please try again and let me know.

**Comment by ryancl** [comment]
Confirmed fixed on my end. Thank you!
