### ISSUE TITLE
Incident type and Incident Priority not displayed in UI

### ISSUE THREAD

**Issue by Martin1196155** [Netflix/dispatch-docker#49]
I run the install.sh file without make any changes in the .env file and after running that file i am able to see 3 containers running and i lauched the dispatcher UI page that also loading fine. when i try to select "Type and Priority" i am seeing as "No Data Available". Please help me why i am getting like this. Do i need to configure in .env to see those values.

**Comment by mvilanova** [comment]
@Martin1196155 these need to be created in the Dispatch Web UI at https://<DISPATCH_URL>/incidents/types and https://<DISPATCH_URL>/incidents/priorities. I'd suggest you create the Service and Document before you create them.
