### ISSUE TITLE
install.sh: sed modification broke the installation

### ISSUE THREAD

**Issue by alexandrosgkesos** [Netflix/dispatch-docker#52]
Commit: 
https://github.com/Netflix/dispatch-docker/commit/68fbbb5ea3fb77ffb48775dac78ce124a6716248

`Generating secret key...
sed: can't read s/^SECRET_KEY=.*/SECRET_KEY="fXq\/9B3DuW?K1Q%:.Et+In#Q9khj:(\\u__1+ZtGehC#TX)vExz"/: No such file or directory
Cleaning up...
`

With:
` sed -i 's/^SECRET_KEY=.*/SECRET_KEY=\"$SECRET_KEY\"/' $DISPATCH_CONFIG_ENV`

It works fine

**Comment by mvilanova** [comment]
@alexandrosgkesos what platform are you running `install.sh` on? The syntax expected by the `-i` flag seems to be different between GNU sed and macOS sed. Let me put a fix together to handle both.

**Comment by mvilanova** [comment]
Ok, fixed merged. Can you try again?

**Comment by alexandrosgkesos** [comment]
@mvilanova It is OpenSuse
Yes it works now. Thank you
