### ISSUE TITLE
Warning: Build Currently Broken Due To GPG Issues in Netflix/dispatch on master

### ISSUE THREAD

**Issue by Osipion** [Netflix/dispatch-docker#53]
Hi, really interesting project, thanks for sharing. Just want to point out that due to issues with GPG keys in Netfix/dispatch (partially?) addressed by [a patch last night](https://github.com/Netflix/dispatch/pull/341), the compose build fails on `gosu` GPG key verification for both web and scheduler builds. I've temporarily pointed [L20](https://github.com/Netflix/dispatch-docker/blob/master/docker-compose.yml#L20) and L35 in my local `docker-compose.yaml` to develop rather than master in an attempt to bypass this issue, but thought I'd add this issue to help others until fixes on develop hit master in Netflix/dispatch.

**Comment by mvilanova** [comment]
Fixed in https://github.com/Netflix/dispatch/pull/351. Thanks for your help!
