### ISSUE TITLE
macOS error: tr: Illegal byte sequence

### ISSUE THREAD

**Issue by chbndrhnns** [Netflix/dispatch-docker#62]
When I run the command to generate the secret key from `./install.sh` on mac OS, I get this error:

```
head /dev/urandom | env LC_CTYPE=C tr -dc "a-z0-9@#%^&*(-_=+)" | head -c 50 | sed -e 's/[\/&]/\\&/g'
tr: Illegal byte sequence
Nf
```

**Comment by mvilanova** [comment]
@chbndrhnns, sorry for the late reply. Is this still happening? I can't repro locally.

**Comment by chbndrhnns** [comment]
I can reproduce.
It fails if `LC_ALL` is set on your system to something different than `C` [source](https://stackoverflow.com/a/23584470/11236740).

**Comment by mvilanova** [comment]
This should be fixed by https://github.com/Netflix/dispatch-docker/pull/73.
