### ISSUE TITLE
Noise From Shared Drive From Google Groups Creation

### ISSUE THREAD

**Issue by alexa-kelley-vim** [Netflix/dispatch-docker#63]
Hello, I'm working on setting up Dispatch for my work environment. However I am running into a problem where Dispatch is creating multiple shared drives per incident. Unfortunately the drives remain even with closing an incident. Is there any way to move the incident creation to a central shared drive to reduce noise? We used shared drives within our environment fairly regularly, so having it taken up with old incidents would become problematic rather quickly. 

Also do you have anything built into the app for cleaning up or removing previously created shared drives?

Image for reference. 

![image](https://user-images.githubusercontent.com/60365635/87087843-d014c780-c201-11ea-92ff-a197fc4753d9.png)

**Comment by mvilanova** [comment]
Hi @alexa-kelley-vim,

Dispatch only creates a shared drive per incident, which seems to be the case looking at the drives names in the screenshot? Unfortunately, the drive plugin doesn't have a method for deleting them at the moment. The good news is that we're moving away from drives and we will be using folders instead (see https://github.com/Netflix/dispatch/pull/205). Perhaps you can help us beta test it? You can replace `master` with `develop` in the [docker compose file](https://github.com/Netflix/dispatch-docker/search?q=master&unscoped_q=master) to build Dispatch from the `develop` branch.

In the future, please open non-docker-related issues in the https://github.com/Netflix/dispatch/ repo.

**Comment by alexa-kelley-vim** [comment]
Ah my apologies on that. I had intended to put this in the dispatch repo. Either way thank you very much for such a swift response. I'll do as you suggest and switch over to the develop branch to beta test the switch to folders. Thank you again!
