### ISSUE TITLE
docker-compose may use wrong context

### ISSUE THREAD

**Issue by theothertomelliott** [Netflix/dispatch-docker#7]
Running install.sh using the fix provided in https://github.com/Netflix/dispatch-docker/pull/6, I encountered the `COPY failed: stat /var/lib/docker/tmp/docker-builder708155561/.nvmrc: no such file or directory` error as in https://github.com/Netflix/dispatch/issues/39.

I got past this by updating the docker-compose to use the root as a context
```
    context: https://github.com/Netflix/dispatch.git#master
    dockerfile: docker/Dockerfile
```

Happy to submit a PR, although want to make sure this isn't specific to my version of Docker (Docker Desktop for Mac 2.2.0.3).

**Comment by kevgliss** [comment]
I believe this has been addressed by a few different PRs. Please let me know if you're still running into issues.
