### ISSUE TITLE
Running the docker on a clean VM fails

### ISSUE THREAD

**Issue by guybarnhartmagen** [Netflix/dispatch-docker#76]
**Describe the bug**
When startign from a clean VM, installing docker and docker compose, then working through the instructions for the docker installation - it fails.

it seems that the docker-compose.yml is pointing to unkown images.
 
**To Reproduce**
run `docker-compose up`

**Expected behavior**
pull all images and run them, it fails to download the web and core images

**Desktop (please complete the following information):**
ubuntu server 20.04 LTS VM

**Comment by kevgliss** [comment]
Are you running the `./install.sh` script or something else? Are there any errors you can provide?

**Comment by mvilanova** [comment]
I was able to repro locally:

```
+ docker-compose pull --ignore-pull-failures
Pulling postgres  ... done
Pulling core      ... done
Pulling web       ... error
Pulling scheduler ... error
ERROR: for web  pull access denied for dispatch-local, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
ERROR: for scheduler  pull access denied for dispatch-local, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
ERROR: pull access denied for dispatch-local, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
++ cleanup
++ '[' 0 -eq 1 ']'
++ echo 'Cleaning up...'
Cleaning up...
++ docker-compose stop
++ DID_CLEAN_UP=1
```
There seems to be an issue with `docker-compose pull --ignore-pull-failures` for local images: https://github.com/docker/compose/issues/3660. Working on a fix.
