### ISSUE TITLE
install.sh COPY ./docker/docker-entrypoint.sh ./docker/.env failure 

### ISSUE THREAD

**Issue by lastlee** [Netflix/dispatch-docker#9]
From the latest in master I am getting the following when running ./install.sh:
```
Step 37/44 : COPY ./docker/docker-entrypoint.sh ./docker/.env $DISPATCH_CONF/
ERROR: Service 'web' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder204368258/docker/.env: no such file or directory
Cleaning up...
```
Looking at this a bit closer, it isn't quite clear what the purpose is for `.env` and `.requirements.txt` is in the repo. Should these be handled by .gitignore?

The `ensure_file_from_example()` seems to be responsible for creating these files, but by default they exist. Just a little unclear.

`SECRET_KEY=.*` does not exist in any of the `.env*` files, so the `sed` update doesn't work -- additionally, if it is made to work there may be an additional space after the `=`.

What does `.env-e` do?

I think a re-work of how the example files are used and generated would be most helpful for getting this project going.

**Comment by inv1sible** [comment]
checkout https://github.com/Netflix/dispatch/issues/39 
https://github.com/TheDahv/dispatch/commit/db0fbda11f5cb51000ef66b24a9bd27fe1ad32d2

**Comment by karl-johan-grahn** [comment]
I also wonder what the `.env-e` file does?

**Comment by kevgliss** [comment]
The entire entrypoint.sh has been removed for a simpler solution.
