### ISSUE TITLE
dropdb: command not found

### ISSUE THREAD

**Issue by kaleming** [Netflix/dispatch-docker#92]
Hi, I am trying to install dispatch with example data.

I first clone `git clone https://github.com/Netflix/dispatch-docker.git`

When I run `./install.sh`, I got `dropdb: command not found`

```
Step 45/46 : LABEL org.opencontainers.image.revision=$SOURCE_COMMIT
 ---> Running in 66e860b3a0c6
Removing intermediate container 66e860b3a0c6
 ---> c1700c6a4a8e
Step 46/46 : LABEL org.opencontainers.image.licenses="https://github.com/netflix/dispatch/blob/${SOURCE_COMMIT:-master}/LICENSE"
 ---> Running in 32e109366118
Removing intermediate container 32e109366118
 ---> ee2a4e977ac8

Successfully built ee2a4e977ac8
Successfully tagged dispatch-local:latest
web uses an image, skipping
scheduler uses an image, skipping

Docker images pulled and built.
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating network "dispatch_default" with the default driver
Creating dispatch_postgres_1 ... done

Setting up database...
Do you want to load example data (WARNING: this will remove all existing database data) (y/N)?y
Downloading example data from Dispatch repository...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  136k  100  136k    0     0  97040      0  0:00:01  0:00:01 --:--:-- 96973
Dropping database dispatch if it already exists...
./install.sh: line 125: dropdb: command not found
Cleaning up...

```

**Comment by kevgliss** [comment]
Hmm, that should exist on the default image (it's a Postgres command). I will take a look.

**Comment by kevgliss** [comment]
I'm not able to recreate this, are you getting a different default image somehow?

**Comment by mvilanova** [comment]
Do you have the Postgres client applications (e.g. dropdb, createdb, etc.) installed on the system where you're running the Bash script?

**Comment by kaleming** [comment]
Hi, I just checked, and there is no postgres installed on my machine:

```
sudo apt-get --purge remove postgresql

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'postgresql' is not installed, so not removed
```

However I have 4 postgres images on ubuntu:

```
docker images | grep postgres

REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE

postgres                            9.6                 1c81a342ea13        2 months ago        200MB
postgres                            12                  d38331307292        2 months ago        314MB
postgres                            12-alpine        3781fe35c6b8        3 months ago        157MB
postgres                            latest              f51c55ac75ed        2 weeks ago         314MB
```
Does this interfere ? 
The only one I am using is postgres:12 for keycloak. I will delete 9.6 and 12-alpine.

**Comment by mvilanova** [comment]
No, it shouldn't. I also have several postgres images and postgres installed locally.

**Comment by mvilanova** [comment]
@kaleming did installing the pg client apps fix the issue?

**Comment by kaleming** [comment]
Hi @mvilanova, I didn`t go further into this issue.

You mean installing running: `sudo apt-get install postgresql-client  ` ?

Where should I add this ? Into some docker-file or my local machine ?

**Comment by mvilanova** [comment]
@kaleming yes, you should install it where you're running the `install.sh`.

**Comment by kaleming** [comment]
Now I got this message:

```
Do you want to load example data (WARNING: this will remove all existing database data) (y/N)?y

Downloading example data from Dispatch repository...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  136k  100  136k    0     0   269k      0 --:--:-- --:--:-- --:--:--  269k
Dropping database dispatch if it already exists...
dropdb: could not connect to database template1: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
Cleaning up...
```

But there is nothing running. Just a postgres container trying to reconnect (during the _### Do you want to load example data_ question).

On stackoverflow says: `Most likely it's because your system (maybe the container) shutdown unexpectedly`

**Comment by mvilanova** [comment]
Hmm can you check that the database server is listening locally on port 5432 before answering yes to load the example data? You can use `nestat` or trying to connect to it using `telnet` or `netcat`. Did you modify the `install.sh` script to connect to a database called `template1` instead of `dispatch`?

**Comment by kaleming** [comment]
There is nothing running when I run: `netstat -na | grep "5432"`

There is only this container restarting:
```
CONTAINER ID   IMAGE      COMMAND                  CREATED          STATUS                          PORTS     NAMES
c10844c0d43a   postgres   "docker-entrypoint.s…"   19 minutes ago   Restarting (1) 25 seconds ago             dispatch_postgres_1

```
That contains this logs.

```
PostgreSQL Database directory appears to contain a database; Skipping initialization

2020-12-14 23:09:55.867 UTC [1] FATAL:  database files are incompatible with server
2020-12-14 23:09:55.867 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 13.1 (Debian 13.1-1.pgdg100+1).
```

**Comment by mvilanova** [comment]
Ah yeah, PostgreSQL won't start unless you upgrade the data directory to the version you're currently using. We have instructions on how to upgrade it [here](https://github.com/Netflix/dispatch-docker#upgrading-from-an-older-version-of-postgres). Alternatively, you can delete the volume used by the container if you don't have any real data in the data directory.

**Comment by mvilanova** [comment]
@kaleming were you able to resolve the issue?

**Comment by kaleming** [comment]
Hi @mvilanova, I couldn't handle to solve it on my computer. Maybe it is related to something I did previously.

I just choose `No`, and it it worked.

`Do you want to load example data (WARNING: this will remove all existing database data) (y/N)?N`.

I will close this issue for a while. because I think this can be related to my machine.

**Comment by fkrauthan** [comment]
I had the same issue and created a merge request to fix the dependency to local installed postgres client tools.
